title: My blog
author: Shirin Kaul
email: shirin.kaul11@gmail.com
description: > # this means to ignore newlines until "show_exerpts:"
  A technical blog about python projects, competitive programming, algorithms and data 
  strucures.
show_excerpts: true # set to true to show excerpts on the homepage
# baseurl: /texture

# Minima date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
sass:
  sass_dir: _sass

permalink: /posts/:title/
texture:
  title: Shirin Kaul
  tagline: Student, developer.
  date_format: "%b %-d, %Y"
  style: red
  showNav: false
  showPicker: false

  # generate social links in footer
  social_links:
    twitter: 
    github:  hyperloop11
    linkedIn: shirin-kaul-b09282190/
    rss: rss
 

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
#header_pages:
# - about.md

# Build settings
theme: texture

plugins:
  - jekyll-seo-tag
#  - jekyll-feed
